---

- name: dr_shutdown_Wrapper.sh
  hosts: all 
  become_user: root
  become_method: sudo
 

  vars:
    
    # mainScript_localpath: "var/lib/awx/projects/new_project"
    mainScript_name: "dr_yml_caller.sh"
    # mainScript_name: "xxdr_shutdown_Wrapper.sh"
    mainScript_localpath: "home/padelaide"
    mainScript_out: "/home/padelaide/dr_shutdown_Wrapper.sh.out"
    mailScript_out: "/home/padelaide/mailScript.out"
    afterStartSleep: "30"

    runcommands: "my args stuff"
    mailAddr: "c@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov"

  tasks:

   - name: run 1 /{{ mainScript_localpath }}/{{ mainScript_name }} script on the remote target servers
     ansible.builtin.script: /{{ mainScript_localpath }}/{{ mainScript_name }} {{ runcommands }} >> {{ mainScript_out }}
     args:
       executable: /bin/bash
            
  #  - name: list Ansible environ
  #   debug: 
  #     msg: "{{ansible_env}}"
       
   #- name: run #2: /opt/VRTSvcs/bin/hastatus script on the remote target servers
   #  ansible.builtin.shell: /opt/VRTSvcs/bin/hastatus
   #  args:
   #   executable: /bin/bash
  
            
