---

- name: dr_shutdown.sh
  hosts: all 
  become_user: root
  become_method: sudo
 

  vars:
   
    task_name: "dr_shutdown"
    task_zip: "dr_shutdown.tar"
    mainScript_name: "dr_shutdown.sh"
    mainScript_basename: "dr_shutdown"
    
    mainScript_localpath: "home/padelaide"
    afterStartSleep: "30"

    mailAddr: "c@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov"

  tasks:

   - name: Copy {{ mainScript_localpath }}/{{ task_zip }} to remote hosts
     ansible.builtin.copy: 
       # src: /{{ mainScript_localpath }}/{{ mainScript_name }}
       src: /{{ mainScript_localpath }}/{{ task_zip }}
       dest: /tmp/{{ task_name }}/
       owner: root
       group: root
       mode: '0777'
        
   - name: Untar /{{ mainScript_localpath }}/{{ task_zip }} over to remote target server
     ansible.builtin.shell: tar xvf /{{ mainScript_remotepath }}/{{ task_zip }}
     args:
       chdir: /{{ mainScript_remotepath }}
     
   - name: Run /{{ mainScript_remotepath }}/{{ mainScript_name }} script on the remote target servers
     ansible.builtin.shell: /{{ mainScript_remotepath }}/{{ mainScript_name }} "{{ inputCommands }}" > {{ logFile }}
     args:
       executable: /bin/bash
            
  
