---

- name: dr_shutdown_Wrapper.sh
  hosts: all 
  become_user: root 

  vars:
    
    # mainScript_localpath: "var/lib/awx/projects/new_project"
    mainScript_name: "dr_shutdown_Wrapper.sh"
    mainScript_localpath: "home/padelaide"
    mainScript_out: "/home/padelaide/dr_shutdown_Wrapper.sh.out"
    mailScript_out: "/home/padelaide/mailScript.out"
    afterStartSleep: "30"

    runcommands: ""
    mailAddr: "c@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov"

  tasks:

   - name: runNEW /{{ mainScript_localpath }}/{{ mainScript_name }} script on the remote target servers
     ansible.builtin.script: 
        cmd: /{{ mainScript_localpath }}/{{ mainScript_name }} {{ runcommands }} > {{ mainScript_out }}
