---

- name: dr_shutdown_wrapper.sh
  hosts: all 
  become_user: root
  become_method: sudo
 

  vars:
    
    # mainScript_localpath: "var/lib/awx/projects/new_project"
    task_name: "dr_shutdown_wrapper"
    mainScript_name: "dr_shutdown_wrapper.sh"
    mainScript_caller: "dr_shutdown_wrapper_caller.sh"
    # mainScript_name: "xxdr_shutdown_Wrapper.sh"
    mainScript_localpath: "home/padelaide"
    mainScript_out: "/home/padelaide/dr_shutdown_wrapper.sh.out"
    mailScript_out: "/home/padelaide/mailScript.out"
    afterStartSleep: "30"

    runcommands: "my args stuff"
    mailAddr: "c@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov"

  tasks:

   - name: copy {{ mainScript_localpath }}/{{ mainScript_name }} to remote hosts
     ansible.builtin.copy: 
       src: /{{ mainScript_localpath }}/{{ mainScript_name }}
       dest: /tmp/{{ task_name }}/
       owner: root
       group: root
       mode: '0777'
     
   - name: run 1. /{{ mainScript_localpath }}/{{ mainScript_caller }} script on the remote target servers
     ansible.builtin.script: /{{ mainScript_localpath }}/{{ mainScript_caller }} {{ runcommands }}
     args:
         executable: /bin/bash
            
  #  - name: list Ansible environ
  #   debug: 
  #     msg: "{{ansible_env}}"
       
   #- name: run #2: /opt/VRTSvcs/bin/hastatus script on the remote target servers
   #  ansible.builtin.shell: /opt/VRTSvcs/bin/hastatus
   #  args:
   #   executable: /bin/bash
  
            
