---

- name: dr_shutdown_Wrapper.sh
  hosts: all 
  become_user: root

  vars:
    
    mainScript_name: "dr_shutdown_Wrapper.sh"
    # mainScript_localpath: "/tower2" 
    # mainScript_localpath: "var/lib/awx/projects/new_project"
    mainScript_out: "dr_shutdown_Wrapper.sh.out"
    mailScript_out: "mailScript.OUT"
    afterStartSleep: "30"

    runcommands: ""
    mailAddr: "c@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov a@irs.gov b@irs.gov"

  tasks:

   - name: runNEW {{ mainScript_localpath }}/{{ mainScript_name }} script on the remote target servers
     #ansible.builtin.script:
     # ansible.builtin.shell: cat dr_shutdown_Wrapper.sh  >> `pwd`/{{ mainScript_out }}
     ansible.builtin.copy:
       src: dr_shutdown_Wrapper.sh 
       dest: /tmp/dr_shutdown_Wrapper.sh.TEST
       owner: foo
       group: foo
       mode: '0777'      


         # cmd: /{{ mainScript_localpath }}/{{ mainScript_name }} {{ runcommands }} > /tmp/{{ mainScript_out }}
         # cmd: dr_shutdown_Wrapper.sh {{ runcommands }} > /tmp/{{ mainScript_out }}
         # cmd: cat dr_shutdown_Wrapper.sh  >> /tmp/{{ mainScript_out }}
         #          cmd: cat dr_shutdown_Wrapper.sh  >> /tmp/{{ mainScript_out }}
        #  remote_src=no
