#!/bin/ksh
#user:
#group:
#interp:

# script name: mainFsApp.ksh

#PAdelaide - IBM/IRS - 10/04/2018
# 
####################################################################################################

# clear the logfile
log="/tmp/$0.logfile.`date '+%m%d%Y-%H%M%S'`.txt"
# >$log

pipe1="/tmp/regular_pipe.$$"
pipe2="/tmp/error_pipe.$$"
trap 'rm "$pipe1" "$pipe2"' EXIT

mkfifo "$pipe1"
mkfifo "$pipe2"
tee -a $log < "$pipe1" &
tee -a $log >&2 < "$pipe2" &

# Redirect output to a logfile as well as their normal locations
exec >"$pipe1"
exec 2>"$pipe2"

# chmod 644 $log

#
# start
#
print "script:[$0]"
date
pwd
id
#
#########################################################

if [ -z "$1" ]; then
   sleepShutdown=600
 else
   sleepShutdown=$1
fi
if [ -z "$2" ]; then
   sleepDepot=300
  else
   sleepDepot=$2
fi

msgOut(){
 print "[`date '+%m/%d/%Y %H:%M:%S'`]: $msg ..."
}

exiT(){
  exit 1
}

print ""
print "################################### [/opt/VRTSvcs/bin/hastatus -sum] #####################################################################"

msg="Running 'hastatus' - 1 of 9 actions...[/opt/VRTSvcs/bin/hastatus -sum]"
msgOut
/opt/VRTSvcs/bin/hastatus -sum
# cat hastatus-sum-Out 

print ""
print "################################### [/disaster_recovery/dr_shutdown.ksh] #################################################################"

msg="Running 'shutdown' -  2 of 9 actions...[/disaster_recovery/dr_shutdown.ksh]"
msgOut
/disaster_recovery/dr_shutdown.ksh
rc=$?
msg="Return Code [/disaster_recovery/dr_shutdown.ksh] [rc:$rc]"
msgOut

print ""
print "################################## [Sleep for [$sleepShutdown] seconds after shutdown] ################################################################################"

msg="Running 'sleep' - 3 of 9 actions...[Sleep for [$sleepShutdown] seconds after shutdown]"
msgOut
sleep "$sleepShutdown"  
rc=$?
msg="Return Code [Woke up from sleep] [rc:$rc]"
msgOut

print ""
print "################################### [/opt/VRTSvcs/bin/hastatus -sum] #####################################################################"

msg="Running 'hastatus' again - 4 of 9 actions...[/opt/VRTSvcs/bin/hastatus -sum]"
msgOut
/opt/VRTSvcs/bin/hastatus -sum
#cat hastatus-sum-Out 

print ""
print "################################### [/opt/VRTSvcs/bin/hastatus -sum]|grep mef_attachments] ###############################################"


msg="Running 'hastatus with grep' - 5 of 9 actions ...[/opt/VRTSvcs/bin/hastatus -sum]|grep mef_attachments]"
msgOut
# searchStr="B  mef_attachments"
/opt/VRTSvcs/bin/hastatus -sum|grep mef_attachments
# cat hastatus-sum-Out |  grep "$searchStr"
rc=$?
if [ $rc -eq 0 ]; then
     msg="This is a MTB server ...[/opt/VRTSvcs/bin/hastatus -sum|grep mef_attachments] [rc:$rc] [searchStr:B  mef_attachments]"
     msgOut
     searchStr="B  mef_attachments"
   else
     msg="This is a MEM server ...[/opt/VRTSvcs/bin/hastatus -sum|grep mef_attachments] [rc:$rc] [searchStr:B  mefapp ]"
     msgOut
     searchStr="B  mefapp "
fi
print ""
print "################################### [/opt/VRTSvcs/bin/hastatus -sum]| grep '$searchStr' | grep -v OFFLINE ###############################"

msg="Running 'hastatus with grep' - 6 of 9 actions ...[/opt/VRTSvcs/bin/hastatus -sum]| grep '$searchStr' | grep -v OFFLINE]"
msgOut

# print "searchStr:[$searchStr]"
print "Greping...[$searchStr]"
# cat hastatus-sum-Out |  grep "$searchStr" | grep -v OFFLINE
/opt/VRTSvcs/bin/hastatus -sum|grep '$searchStr' | grep -v OFFLINE
rc=$?
if [ $rc -eq 0 ]; then
     msg="WARNING: [$searchStr]  NOT OFFLINE, cannot Deport now ...exiting script"
     msgOut
     exiT
   else
     msg="[$searchStr] SUCCESSFULLY OFFLINED: will proceed to deport..."
     msgOut
fi


print ""
print "################################################# Deport ##################################################################################"
msg="Running 'Deport' - 7 of 9 actions ...[/disaster_recovery/dr_deport.ksh]"
msgOut
/disaster_recovery/dr_deport.ksh
rc=$?
msg="Return Code [/disaster_recovery/dr_deport.ksh] [rc:$rc]"
msgOut

print ""
print "############################################ Sleep $sleepDepot seconds after Deport ##################################################################"
msg="Running 'sleep' - 8 of 9 actions...[Sleep for $sleepDepot seconds after Deport]"
msgOut
sleep "$sleepDepot" 
rc=$?
msg="Return Code [Woke up from sleep] [rc:$rc]"
msgOut

print ""
print "################################################# vxdg list after Deport ##################################################################"
msg="Running 'vxdg list' -  9 of 9 actions ...[ /usr/sbin/vxdg list ]"
msgOut
/usr/sbin/vxdg list
rc=$?
msg="Return Code [/usr/sbin/vxdg list] [rc:$rc]"
msgOut

chmod 644 $log
exit
# ==================== #
# END OF SHELL SCRIPT. #
# ==================== #
