---

- name: run2task_param.sh
  hosts: all

####

  vars:

    task_name: "run2task"
    task_zip: "run2task_wrapper.tar"

    mainScript_name: "run2task.sh"
    mainScript_caller: "run2task_wrapper_caller.sh"
    mainScript_localpath: "home/padelaide"


  tasks:

   - name: Copy /{{ mainScript_localpath }}/{{ task_zip }} over to remote target server
     ansible.builtin.copy:
       src: /{{ mainScript_localpath }}/{{ task_zip }}
       dest: /tmp/{{ task_name }}/
       owner: root
       group: root
       mode: u+rwx

   - name: Run /{{ mainScript_localpath }}/{{ mainScript_caller }} script on the remote target servers
     ansible.builtin.script: /{{ mainScript_localpath }}/{{ mainScript_caller }}
     args:
       executable: /bin/bash
