---

- name: run2task_param.sh
  hosts: all

####

  vars:

    task_name: "run2task_yml"
    task_zip: "run2task_yml_wrapper.tar"

    mainScript_name: "run2task_param.sh"
    mainScript_caller: "run2task_wrapper_caller.sh"
    mainScript_localpath: "home/padelaide"
    mainScript_remotepath: "tmp/{{ task_name }}
    
    inputCommands: "testing inputCommands"
    logFile: "testing logFile"
  
  tasks:

   - name: Copy /{{ mainScript_localpath }}/{{ task_zip }} over to remote target server
     ansible.builtin.copy:
       src: /{{ mainScript_localpath }}/{{ task_zip }}
       dest: /{{ mainScript_remotepath }}/
       owner: root
       group: root
       mode: u+rwx

   - name: Untar /{{ mainScript_localpath }}/{{ task_zip }} over to remote target server
     ansible.builtin.shell: tar xvf /{{ mainScript_remotepath }}/{{ task_zip }}
     args:
       chdir: /{{ mainScript_remotepath }}
     
   - name: Run /{{ mainScript_remotepath }}/{{ run2task_param.sh }} script on the remote target servers
     ansible.builtin.shell: /{{ mainScript_remotepath }}/{{ run2task_param.sh }} {{ task_name }}
     args:
       executable: /bin/bash
       
   - name: Run /tmp/{{ task_name }}/{{ run2task_param.sh }} script on the remote target servers
     ansible.builtin.shell: /{{ mainScript_remotepath }}/{{ run2task_param.sh }} {{ task_name }}
     args:
       executable: /bin/bash    
