---

- name: status-parasoft-Q.yml
  hosts: all

# call: status-parasoft-Q.ksh
####

  vars:

    task_name: "status-parasoft-Q"
    task_zip: "status-parasoft-Q.tar"
    mainScript_name: "status-parasoft-Q.ksh"
    mainScript_localpath: "home/padelaide"
    mainScript_remotepath: "tmp/{{ task_name }}"
    logFile: "/tmp/{{ task_name }}.reportOut"
    mailScript_name: "mailScript.sh"
    mailScript_basename: "mailScript"
         
    # mailAddr var to be passed fron Tempelate at launch # 
    # mailAddr: ""
  
  tasks:

   - name: Copy /{{ mainScript_localpath }}/{{ task_zip }} over to remote target server
     ansible.builtin.copy:
       src: /{{ mainScript_localpath }}/{{ task_zip }}
       dest: /{{ mainScript_remotepath }}/
       owner: root
       group: root
       mode: u+rwx

   - name: Untar /{{ mainScript_remotepath }}/{{ task_zip }} on the remote target server
     ansible.builtin.shell: tar xvf /{{ mainScript_remotepath }}/{{ task_zip }}
     args:
       chdir: /{{ mainScript_remotepath }}
     
   - name: Run /{{ mainScript_remotepath }}/{{ mainScript_name }} script on the remote target servers
     ansible.builtin.shell: /{{ mainScript_remotepath }}/{{ mainScript_name }} > {{ logFile }}
     args:
       executable: /bin/bash
       
   - name: Run /{{ mainScript_remotepath }}/{{ mailScript_name }} script on the remote target servers
     ansible.builtin.shell: /{{ mainScript_remotepath }}/{{ mailScript_name }} "{{ mailAddr }} {{ logFile }}"  >  /tmp/{{ mailScript_basename }}.{{ task_name }}.reportOut
     args:
       executable: /bin/bash    


